on:
  issues:
    types: [closed, deleted]
  pull_request:
    types: [closed]
  workflow_dispatch:


name: Close Jira ticket corresponding to GitHub Issue/PR

jobs:
  main:
    runs-on: ubuntu-latest
    name: Main
    steps:
    - name: Dump context
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Search using issue link
      if: ${{ github.event.issue }}
      id: search-issue
      uses: tomhjp/gajira-search@master
      with:
        jql: 'project = "VAULT" and issuetype = "GH Issue" and cf[10089]="${{ github.event.issue.html_url }}"' # cf[10089] == Issue Link custom field

    - name: Search using PR link
      if: ${{ github.event.pull_request }}
      id: search-pr
      uses: tomhjp/gajira-search@master
      with:
        jql: 'project = "VAULT" and issuetype = "GH Issue" and cf[10089]="${{ github.event.pull_request.html_url }}"' # cf[10089] == Issue Link custom field

    - name: Close Jira for Issue
      if: ${{ github.event.issue }}
      uses: atlassian/gajira-transition@v2.0.1
      with:
        issue: ${{ steps.search-issue.outputs.issue }}
        transition: Done

    - name: Close Jira for PR
      if: ${{ github.event.pull_request && github.event.pull_request.merged == true }}
      uses: atlassian/gajira-transition@v2.0.1
      with:
        issue: ${{ steps.search-pr.outputs.issue }}
        transition: Done
